name: Build release candidate

env:
  OUTPUT_PATH: ${{ github.workspace }}/.nupkg
  DOTNET_VERSION: "3.1.100"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Dotnet ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Generate packages
        run: dotnet fake run ./build.fsx --target Release

      - name: Set Version
        run: dotnet fake run ./build.fsx --target SetVersionForCI

      - name: Publish release packages
        uses: actions/upload-artifact@v1
        with:
          name: packages
          path: ${{ env.OUTPUT_PATH }}

      - name: Create Release Issue
        uses: ./github/actions/create-issue
        with:
          token: ${{ env.GITHUB_TOKEN }}
          title: Release $package_version ready for review
